import { BsHash, BsSearch, BsChevronDoubleRight, BsCardText, BsQuestionCircle, BsTranslate, BsStopwatch, BsWalletFill } from 'react-icons/bs'

export const arrayItems = [
    {
        name: "Q&A",
        id: "q&a",
        description: "Answer questions based on existing knowledge",
        message: "Question and Answers:",
        icon: BsQuestionCircle,
        iconColor: "#763FDD",
        option: {
            model: "text-davinci-003",
            temperature: 0,
            max_tokens: 100,
            top_p: 1,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "Grammer Correction",
        id: "grammerCorrection",
        description: "Corrects sentences into standard English.",
        message: "Correct this sentences:",
        icon: BsCardText,
        iconColor: "#EF4146",
        option: {
            model: "text-davinci-003",
            temperature: 0,
            max_tokens: 100,
            top_p: 1,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "Summarize for a 2nd grader",
        id: "summary",
        description: "Translates difficult text into simpler concepts.",
        icon: BsChevronDoubleRight,
        message: "Translates difficult text into simpler concepts:",
        iconColor: "#F3A741",
        option: {
            model: "text-davinci-003",
            temperature: 0.7,
            max_tokens: 64,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "English to Other languages",
        id: "translate",
        description: "Translates English text into French, Spanish and Japanese.",
        icon: BsSearch,
        iconColor: "#8151DF",
        message: "English to Telugu:",
        option: {
            model: "text-davinci-003",
            temperature: 0.3,
            max_tokens: 100,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "Python to natural language",
        id: "Pythontonaturallanguage",
        description: "Python to natural language.",
        icon: BsHash,
        iconColor: "#763FDD",
        message: "Python to natural language:",
        option: {
            model: "code-davinci-002",
            temperature: 0,
            max_tokens: 64,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0
        },
    },
    {
        name: "Explain code",
        id: "explainCode",
        description: "Explain a complicated piece of code.",
        icon: BsHash,
        iconColor: "#F4B153",
        message: "Explain code:",
        option: {
            model: "code-davinci-002",
            temperature: 0,
            max_tokens: 64,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "Translate programming languages",
        id: "tpl",
        description: "To translate from one programming language to another we can use the comments to specify the source and target languages.",
        icon: BsTranslate,
        iconColor: "#24C087",
        message: "Translate programming languages To JavaScript:",
        option: {
            model: "code-davinci-002",
            temperature: 0,
            max_tokens: 54,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "Calculate Time Complexity",
        id: "CalculateTimeComplexity",
        description: "Find the time complexity of a function.",
        icon: BsStopwatch,
        iconColor: "#F4B153",
        message: "Calculate Time Complexity:",
        option: {
            model: "text-davinci-003",
            temperature: 0,
            max_tokens: 64,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0,
        },
    },
    {
        name: "Interview questions",
        id: "Interviewquestions",
        description: "Interview questions.",
        icon: BsWalletFill,
        iconColor: "#DE5BDC",
        message: "Interview questions:",
        option: {
            model: "text-davinci-003",
            temperature: 0.5,
            max_tokens: 150,
            top_p: 1.0,
            frequency_penalty: 0.0,
            presence_penalty: 0.0
        },
    }
];